---
abstract: 'Perl module to represent MQTT messages'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MQTT
requires:
  Getopt::Long: 0
  IO::Select: 0
  IO::Socket::INET: 0
  Module::Pluggable: 0
  Net::Pcap: 0
  Pod::Usage: 0
  Time::HiRes: 0
resources:
  bugtracker: http://github.com/beanz/net-mqtt-perl/issues
  repository: git://github.com/beanz/net-mqtt-perl.git
version: 1.110170
